void cleanup(void);
Sprite *createSpriteFromLine(char *line);
Sprite *getSprite(char *spriteName);
void initEntities(void);
Player *initPlayer(void);
bool initSDL(void);
bool loadSprites(void);
bool loadSpriteFile(SpriteTuple *tuple);
bool loadTexture(void);
void setWindowIcon(void);
