void doInput(void);
void doGame(void);
void doMainMenu(void);
void doPauseMenu(void);
void doMovement(void);
void doEntities(void);
void changeOption(SDL_KeyboardEvent* event);
void movePlayer(SDL_KeyboardEvent *event);
void drawComplete(void);
void drawEntities(void);
void drawPlayer(void);
void drawScene(void);
void drawGround(void);
void drawLines(void);
void capFrameRate(long *then, float *remainder);
void outOfBounds(void);
void checkCollision(void);
bool checkCanMove(Entity *entity, int nx, int ny);
void stopAndRecentre(void);
bool onSwitch(Entity *e);
